# Generated by Django 5.2.1 on 2025-06-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_track_tracklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracklog',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
