# Generated by Django 5.2.1 on 2025-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_tracklog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='description',
        ),
        migrations.RemoveField(
            model_name='track',
            name='title',
        ),
        migrations.AddField(
            model_name='track',
            name='goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='New Track', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='unit',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
