# Generated by Django 5.2.1 on 2025-06-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_track_description_remove_track_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
