### register
POST http://127.0.0.1:8000/account/register/
Content-Type: application/json

{
    "email": "farhang@example.com",
    "password1": "farhang1234",
    "password2": "farhang1234"
}

### login
POST http://localhost:8000/api/account/
Content-Type: application/json

{
    "email": "mehrnoosh@example.com",
    "password": "mehrnoosh1234"
}


### logout
POST http://localhost:8000/api/account/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDE2NzU0LCJpYXQiOjE3NDkwMTY0NTQsImp0aSI6IjAxOTk4YzRlMTI1MTQ0NzlhYzQyYTk3OTM1YjQ2ZGE3IiwidXNlcl9pZCI6IjE1ZTkwMWYyLTQ3YzYtNGM3MS1hNmMyLTE5OWY4YzQ0OTkyZSJ9.trl1mwz5m4ih7WHWvQRcLrAGiqSJHURkR_4rU9Gp3tg
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0OTEwMjg1NCwiaWF0IjoxNzQ5MDE2NDU0LCJqdGkiOiI3ODQ0MThhMjVkNGU0YWQ5ODcxODYwZGVjZTkwZmZhMyIsInVzZXJfaWQiOiIxNWU5MDFmMi00N2M2LTRjNzEtYTZjMi0xOTlmOGM0NDk5MmUifQ.ak85dpj0TZrKGswaCM8JvaguUpaFFtziAB5hlY6gOi8"
}


### user_profile
GET http://localhost:8000/api/account/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDIxODQzLCJpYXQiOjE3NDkwMjE1NDMsImp0aSI6IjRiNzRhN2VhNmJjZjQ1OWZhZjk0NTdlOWJjYWZiY2I3IiwidXNlcl9pZCI6IjcxZDg4NWI2LTdmMmYtNDlhYi1hNjQyLTFhZDE5NjUxNDAzZSJ9.Z0DGBD6BEfsGdsL510JBaV9EFR1dwRSXorb_wNFrCGU
Content-Type: application/json


### edit_profile
PUT http://localhost:8000/api/account/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDIyMzM5LCJpYXQiOjE3NDkwMjIwMzksImp0aSI6ImNlOTE4ZmEwMjE3MjRjNjk5MzgyNTZhOWU1NzI3NzI4IiwidXNlcl9pZCI6IjcxZDg4NWI2LTdmMmYtNDlhYi1hNjQyLTFhZDE5NjUxNDAzZSJ9.waHxZ04ZNkJdRinYahLG7rXi0Dd_weGzP3bdNBY6CEk
Content-Type: application/json

{
    "username": "Merhnoosh_dev",
    "email": "mehrnoosh@example.com",
    "first_name": "Mehrnoosh",
    "last_name": "Shoolestani",
    "phone": "09207443796"
}

